// <auto-generated />
namespace OopRestaurant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addrequiredvalidationtoMenuItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrequiredvalidationtoMenuItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201802181415278_add required validation to MenuItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
